[language-server.astro-language-server]
command = "astro-ls"
args = ["--stdio"]

[[language]]
name = "astro"
language-servers = ["astro-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "astro"] }
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "markdown"
text-width = 80
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "markdown", "--prose-wrap", "always"] }
auto-format = true
