[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "babel"] }
auto-format = true
