[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "babel"] }
auto-format = true
